version: '3'
services:
  cms:
    networks:
      - facile
    build: .
    restart: always
    ports:
      - '24040:24040'
    volumes:
      - .:/home/node/app
networks:
  facile:
    external:
      name: facile
