version: '3'
services:
  cms:
    networks:
      - facile
    build: .
    ports:
      - '24040:24040'
      - '24050:24050'
    volumes:
      - .:/home/node/cms
    entrypoint: 'npm run dev'
networks:
  facile:
    external:
      name: facile
